version: '3.8'
services:
  postgres:
    image: 'postgres:14.5-alpine'
    restart: always
    container_name: 'postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=UkrGas'
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db:/docker-entrypoint-initdb.d
      - ukrGas-data:/var/lib/postgresql/data
  application:
    build: ./
    restart: always
    container_name: 'application'
    ports:
      - "8443:8443"
    depends_on:
      - postgres
volumes:
  ukrGas-data: