version: '3.8'
services:

  postgres:
    image: 'postgres:14.5-alpine'
    container_name: 'postgres'
    restart: always
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=UkrGas'
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db:/docker-entrypoint-initdb.d
      - ukrGas-data:/var/lib/postgresql/data

  redis:
    image: "redis:7-alpine"
    container_name: 'redis'
    restart: always
    ports:
      - "6379:6379"
    environment:
      - 'REDIS_PASSWORD=password'
    volumes:
      - ukrGas-cache:/var/lib/redis/data

  application:
    build: ./
    restart: always
    container_name: 'application'
    ports:
      - "8443:8443"
    depends_on:
      - postgres
      - redis

volumes:
  ukrGas-data:
  ukrGas-cache:
